import React, { useState } from "react";
import Head from "next/head";
import PageTop from "@/components/section/pagetop";
import ContactForm from "@/components/section/contact_form";
import Footer from "@/components/common/footer";
import FormSucessPopup from "@/components/section/form_sucess_popup";

import styles from "./index.module.css";

export default function ContactPage() {
  const [formSucess, setFormSucess] = useState(false);
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PageTop />
        <ContactForm setFormSucess={setFormSucess} />
        <Footer />
        {formSucess ? <FormSucessPopup setFormSucess={setFormSucess} /> : null}
      </main>
    </>
  );
}
