import React from "react";
import Head from "next/head";
import SecOne from "@/components/section/sec_one";
import SecTwo from "@/components/section/sec_two";
import Footer from "@/components/common/footer";

import styles from "@/pages/index.module.css";

export default function Home({ products, users }) {
  return (
    <>
      <Head>
        <title>Nuox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SecOne products={products} />
        <SecTwo users={users} />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://dummyjson.com/products/?limit=5");
  const products = await res.json();
  const resp = await fetch("https://dummyjson.com/users/?limit=8");
  const users = await resp.json();

  return {
    props: {
      products,
      users,
    },
  };
}
